/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App_ui;

/**
 *
 * @author admin
 */
public class QuanLyKhoHang extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyBanhPanel
     */
    public QuanLyKhoHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTieuDe = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblMaBanh = new javax.swing.JLabel();
        lblTenBanh = new javax.swing.JLabel();
        lblGiaTien = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        lblSizeBanh = new javax.swing.JLabel();
        txtMaBanh = new javax.swing.JTextField();
        txtTenBanh = new javax.swing.JTextField();
        txtGiatien = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        rdoS = new javax.swing.JRadioButton();
        rdoM = new javax.swing.JRadioButton();
        btnTaoMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        BtnXoa = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rdoL = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        lblTieuDe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTieuDe.setForeground(new java.awt.Color(255, 0, 0));
        lblTieuDe.setText("QUẢN LÝ KHO HÀNG");

        lblMaBanh.setText("Mã Bánh");

        lblTenBanh.setText("Tên Bánh");

        lblGiaTien.setText("Giá Tiền");

        lblSoLuong.setText("Số Lượng");

        lblSizeBanh.setText("Size Bánh");

        buttonGroup1.add(rdoS);
        rdoS.setText("S");

        buttonGroup1.add(rdoM);
        rdoM.setText("M");

        btnTaoMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/anh_18.jpg"))); // NOI18N
        btnTaoMoi.setText("Thêm");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/anh_20.jpg"))); // NOI18N
        btnThem.setText("Làm Mới");

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/update.jpg"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");

        BtnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/remove.jpg"))); // NOI18N
        BtnXoa.setText("Xóa");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã bánh", "Tên bánh", "Số lượng ", "Size bánh", "Giá tiền", "Ngày nhập"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        buttonGroup1.add(rdoL);
        rdoL.setText("L");

        jLabel1.setText("Ngày Nhập");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMaBanh)
                                    .addComponent(lblTenBanh)
                                    .addComponent(lblSoLuong)
                                    .addComponent(lblSizeBanh)
                                    .addComponent(lblGiaTien)
                                    .addComponent(jLabel1))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdoS)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoM)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoL))
                                    .addComponent(txtGiatien, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(txtMaBanh, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(txtTenBanh, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(jTextField1)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(lblTieuDe))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnTaoMoi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnCapNhat)
                                .addGap(18, 18, 18)
                                .addComponent(BtnXoa)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTieuDe)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaBanh)
                    .addComponent(txtMaBanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenBanh)
                    .addComponent(txtTenBanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSizeBanh)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoS)
                        .addComponent(rdoM)
                        .addComponent(rdoL)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblSoLuong))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiatien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGiaTien))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaoMoi)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhat)
                    .addComponent(BtnXoa))
                .addGap(61, 61, 61)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnXoa;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnTaoMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblGiaTien;
    private javax.swing.JLabel lblMaBanh;
    private javax.swing.JLabel lblSizeBanh;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenBanh;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JRadioButton rdoL;
    private javax.swing.JRadioButton rdoM;
    private javax.swing.JRadioButton rdoS;
    private javax.swing.JTextField txtGiatien;
    private javax.swing.JTextField txtMaBanh;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenBanh;
    // End of variables declaration//GEN-END:variables
}
