/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package APP_UI;

import Dao.BanhDao;
import Helpers.DataValidator;
import Helpers.MessageDialogHelper;
import Model.Banh;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class QuanLyBanhPanel extends javax.swing.JPanel {
 private  MainForm parentForm;
 private DefaultTableModel tblModel;
 int index = 0;
    /**
     * Creates new form QuanLyBanhPanel
     */
    public QuanLyBanhPanel() {
        initComponents();
        initTable();
        loadDaTaToTable();
        
    }

     private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã Bánh"," Tên Bánh","Size Bánh","Số lượng","Giá tiền","Ngày Nhập","Mã NV Nhập"});
        tblBanh.setModel(tblModel);
    }
      private void loadDaTaToTable(){
        try{
            BanhDao dao = new BanhDao();
            List<Banh> list = dao.finadAll();
            tblModel.setRowCount(0);
            for (Banh x : list) {
                tblModel.addRow(new Object[]{
                    x.getMaBanh(),x.getTenBanh(),x.getSizeBanh().equals("S")? "S" : x.getSizeBanh().equals("M")? "M":"L",
                    x.getSoLuong(),x.getGiaTien(),x.getNgayNhap(),x.getMaNhanVien()
                });
            }
            tblModel.fireTableDataChanged();
        } catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(),"Lỗi");
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblMaBanh = new javax.swing.JLabel();
        lblTenbanh = new javax.swing.JLabel();
        lblSizebanh = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        lblGiaTien = new javax.swing.JLabel();
        lblNgayNhap = new javax.swing.JLabel();
        txtMaBanh = new javax.swing.JTextField();
        txtTenBanh = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtGiaTien = new javax.swing.JTextField();
        txtNgayNhap = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnThem = new javax.swing.JButton();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        rdoSizeS = new javax.swing.JRadioButton();
        rdoSizeM = new javax.swing.JRadioButton();
        rdoSizeL = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBanh = new javax.swing.JTable();
        lblMaNV = new javax.swing.JLabel();
        txtMaNVNhap = new javax.swing.JTextField();
        lblTimBanh = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Quản Lý Kho Hàng");

        lblMaBanh.setText("Mã Bánh");

        lblTenbanh.setText("Tên Bánh");

        lblSizebanh.setText("Size Bánh");

        lblSoLuong.setText("Số Lượng");

        lblGiaTien.setText("Giá Tiền");

        lblNgayNhap.setText("Ngày Nhập");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnThemMoi.setText("Thêm Mới");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoSizeS);
        rdoSizeS.setText("S");

        buttonGroup1.add(rdoSizeM);
        rdoSizeM.setText("M");

        buttonGroup1.add(rdoSizeL);
        rdoSizeL.setText("L");

        tblBanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBanhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBanh);

        lblMaNV.setText("Mã NV Nhập");

        lblTimBanh.setText("Tìm Bánh");

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblMaNV))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTenbanh)
                                    .addComponent(lblMaBanh)
                                    .addComponent(lblSizebanh)
                                    .addComponent(lblSoLuong)
                                    .addComponent(lblGiaTien)
                                    .addComponent(lblNgayNhap))))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txtMaBanh)
                            .addComponent(txtTenBanh)
                            .addComponent(txtSoLuong)
                            .addComponent(txtGiaTien)
                            .addComponent(txtNgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoSizeS)
                                .addGap(19, 19, 19)
                                .addComponent(rdoSizeM)
                                .addGap(27, 27, 27)
                                .addComponent(rdoSizeL))
                            .addComponent(txtMaNVNhap)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThem)
                                    .addComponent(lblTimBanh))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThemMoi)
                                        .addGap(31, 31, 31)
                                        .addComponent(btnCapNhat))
                                    .addComponent(txtTimKiem))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(btnXoa))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(btnTimKiem))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaBanh)
                    .addComponent(txtMaBanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenbanh)
                    .addComponent(txtTenBanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSizebanh)
                    .addComponent(rdoSizeS)
                    .addComponent(rdoSizeM)
                    .addComponent(rdoSizeL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoLuong)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGiaTien)
                    .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayNhap)
                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNV)
                    .addComponent(txtMaNVNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnThemMoi)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimBanh)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        txtMaBanh.setText("");
        txtTenBanh.setText("");
        txtSoLuong.setText("");
        txtGiaTien.setText("");
        txtNgayNhap.setText("");
        txtMaNVNhap.setText("");
        txtTimKiem.setText("");
   
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmply(txtMaBanh, sb,"Mã bánh cần phải nhập");
        DataValidator.validateEmply(txtTenBanh, sb,"Tên Bánh cần phải nhập");
        DataValidator.validateEmply(txtSoLuong, sb,"Số lượng Bánh cần phải nhập");
        DataValidator.validateEmply(txtGiaTien, sb,"Giá Tiền Bánh cần phải nhập");
        DataValidator.validateEmply(txtNgayNhap, sb,"Ngày Nhập Bánh cần phải nhập");
        DataValidator.validateEmply(txtMaNVNhap, sb,"Mã nhân viên nhập Bánh cần phải nhập");
        
        if(sb.length()>0){
            MessageDialogHelper.showErrorDialog(parentForm,sb.toString(),"Lỗi");
            return;
        }
        try{
            Banh banh = new Banh();
            banh.setMaBanh(txtMaBanh.getText());
            banh.setTenBanh(txtTenBanh.getText());
            banh.setSizeBanh(rdoSizeS.isSelected()? "S" : rdoSizeM.isSelected()? "M": "L");
            banh.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
            banh.setGiaTien(Float.parseFloat(txtGiaTien.getText()));
            banh.setNgayNhap(txtNgayNhap.getText());
            banh.setMaNhanVien(txtMaNVNhap.getText());
              BanhDao dao = new BanhDao();
              if(dao.insert(banh)){
                  MessageDialogHelper.showMessageDialog(parentForm,"Thông tin bánh đã được lưu","Thông báo");
                  loadDaTaToTable();
              } else {
                  MessageDialogHelper.showMessageDialog(parentForm,"thông tin bánh không lưu được", "Thông báo");
              }
        } catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(),"Lỗi");
        }    
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
            StringBuilder sb = new StringBuilder();
          DataValidator.validateEmply(txtMaBanh, sb,"Mã bánh cần phải nhập");
        DataValidator.validateEmply(txtTenBanh, sb,"Tên Bánh cần phải nhập");
        DataValidator.validateEmply(txtSoLuong, sb,"Số lượng Bánh cần phải nhập");
        DataValidator.validateEmply(txtGiaTien, sb,"Giá Tiền Bánh cần phải nhập");
        DataValidator.validateEmply(txtNgayNhap, sb,"Ngày Nhập Bánh cần phải nhập");
          DataValidator.validateEmply(txtMaNVNhap, sb,"Mã nhân viên nhập Bánh cần phải nhập");
        if(sb.length()>0){
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(),"lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(parentForm, "bạn có muốn cập nhật thông tin bánh không?","hỏi")==JOptionPane.NO_OPTION){
            return;
        }
           
     try{
              Banh banh = new Banh();
            banh.setMaBanh(txtMaBanh.getText());
            banh.setTenBanh(txtTenBanh.getText());
            banh.setSizeBanh(rdoSizeS.isSelected()?"S":rdoSizeM.isSelected()?"M":"L");
            banh.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
            banh.setGiaTien(Float.parseFloat(txtGiaTien.getText()));
            banh.setNgayNhap(txtNgayNhap.getText());
            banh.setMaNhanVien(txtMaNVNhap.getText());
            
            BanhDao dao = new BanhDao();
            if(dao.update(banh)){
                MessageDialogHelper.showMessageDialog(parentForm, "Thông tin bánh đã được cập nhật", "Thông báo");
                loadDaTaToTable();
            } else {
                 MessageDialogHelper.showMessageDialog(parentForm, "thông tin bánh không được cập nhật ", "Cảnh báo");
            }
     }catch(Exception e){
         e.printStackTrace();
             MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(),"Lỗi");}
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
            DataValidator.validateEmply(txtMaBanh, sb, "mã bánh không được để trống");
       
        if(sb.length()>0){
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(),"lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(parentForm, "bạn có muốn xóa thông tin bánh không?","hỏi")==JOptionPane.NO_OPTION){
            return;
        }
        try{
            BanhDao dao = new BanhDao();
            if(dao.deleteByMaBanh(txtMaBanh.getText())){
                MessageDialogHelper.showMessageDialog(parentForm, "Thông tin bánh đã được xóa", "Thông báo");
                loadDaTaToTable();
                btnThemMoiActionPerformed(evt);
            } else {
                 MessageDialogHelper.showMessageDialog(parentForm, "Thông tin bánh không xóa được do lỗi ", "Cảnh báo");
            }
        } catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(),"Lỗi");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblBanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBanhMouseClicked
        // TODO add your handling code here:
          try{
            int row = tblBanh.getSelectedRow();
            if(row>=0){
                String id = (String) tblBanh.getValueAt(row, 0);
                BanhDao dao = new BanhDao();
                Banh banh = dao.findByIMaBanh(id);
                
                if(banh != null){
                    txtMaBanh.setText(banh.getMaBanh());
                    txtTenBanh.setText(banh.getTenBanh());
                    rdoSizeS.setSelected(banh.getSizeBanh().equals("S")? true:false);
                    rdoSizeM.setSelected(banh.getSizeBanh().equals("M")? true:false);
                    rdoSizeL.setSelected(banh.getSizeBanh().equals("L")? true:false);
                    txtSoLuong.setText(Integer.toString(banh.getSoLuong()));
                    txtGiaTien.setText(Float.toString(banh.getGiaTien()));
                    txtNgayNhap.setText(banh.getNgayNhap());
                    txtMaNVNhap.setText(banh.getMaNhanVien());
                }
            }
        }catch(Exception e){
            e.printStackTrace();
              MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(),"Lỗi");
        }
    }//GEN-LAST:event_tblBanhMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
         StringBuilder sb = new StringBuilder();
            DataValidator.validateEmply(txtTimKiem, sb, "mã tìm kiếm không được để trống");
       
        if(sb.length()>0){
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(),"lỗi");
            return;
        }
         try{
            BanhDao dao = new BanhDao();
            if(dao.findByIMaBanh(txtTimKiem.getText()) != null){
                MessageDialogHelper.showMessageDialog(parentForm, "Thông tin bánh đã được tìm thấy", "Thông báo");                   
           Banh banh = dao.findByIMaBanh(txtTimKiem.getText());
                txtMaBanh.setText(banh.getMaBanh());
                    txtTenBanh.setText(banh.getTenBanh());
                    rdoSizeS.setSelected(banh.getSizeBanh().equals("S")? true:false);
                    rdoSizeM.setSelected(banh.getSizeBanh().equals("M")? true:false);
                    rdoSizeL.setSelected(banh.getSizeBanh().equals("L")? true:false);
                    txtSoLuong.setText(Integer.toString(banh.getSoLuong()));
                    txtGiaTien.setText(Float.toString(banh.getGiaTien()));
                    txtNgayNhap.setText(banh.getNgayNhap());
                    txtMaNVNhap.setText(banh.getMaNhanVien());

            } else {
                 MessageDialogHelper.showMessageDialog(parentForm, "Thông tin bánh không được tìm thấy ", "Cảnh báo");
                 btnThemMoiActionPerformed(evt);
            }
        } catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(),"Lỗi");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblGiaTien;
    private javax.swing.JLabel lblMaBanh;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblNgayNhap;
    private javax.swing.JLabel lblSizebanh;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenbanh;
    private javax.swing.JLabel lblTimBanh;
    private javax.swing.JRadioButton rdoSizeL;
    private javax.swing.JRadioButton rdoSizeM;
    private javax.swing.JRadioButton rdoSizeS;
    private javax.swing.JTable tblBanh;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtMaBanh;
    private javax.swing.JTextField txtMaNVNhap;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenBanh;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
